% Example_run.m
 % Automatically generated by Netflux on 17-Jan-2018

 % Load parameters
 [params,y0] = Example_loadParams();

 % Run single simulation
 tspan = [0 10];
 options = [];
 [t,y] = ode23(@Example,tspan,y0,options,params);

 % Plot results
 figure;
 plot(t,y);
 xlabel('Time (sec)');
 ylabel('Fractional Species Activation');
 speciesNames = params{4};
 legend(speciesNames); 
