% Example_run.m
 % Automatically generated by Netflux on 17-Jan-2018

 % Load parameters
 [params,y0] = Example_loadParams();

 % Run single simulation
 tspan = [0 10];
 options = [];
 [t,y] = ode23(@Example,tspan,y0,options,params);
 
 tspan = [10 20];
 options = [];
 [t2,y2] = ode23(@Example,tspan,y(end,:),options,params);
 % Plot results
 figure;
 tf = vertcat(t,t2);
 yf = vertcat(y,y2);
 plot(tf,yf);
 xlabel('Time (sec)');
 ylabel('Fractional Species Activation');
 speciesNames = params{4};
 legend(speciesNames);